name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:  # ğŸ‘ˆ ì—¬ê¸°ì— í™˜ê²½ ë³€ìˆ˜ ì£¼ì…
      VITE_GOOGLE_CLIENT_ID: ${{ secrets.VITE_GOOGLE_CLIENT_ID }}
      VITE_GOOGLE_API_KEY: ${{ secrets.VITE_GOOGLE_API_KEY }}

    steps:
      - uses: actions/checkout@v4

      - run: npm ci
      - run: npm run build  # âœ… ì—¬ê¸°ì„œ envê°’ë“¤ì´ Vite ë¹Œë“œì— ì‚¬ìš©ë¨

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_FCMM }}
          channelId: live
          projectId: fcmm
